when:
  - event: tag
    ref: refs/tags/v*
  - event: push
    branch: master
    path:
      include:
        - "app/**"
        - "build.gradle.kts"
        - "settings.gradle.kts"
        - "gradle/**"
        - ".woodpecker.yml"

steps:
  - name: build-debug
    image: mingc/android-build-box:latest
    commands:
      - ./gradlew assembleDebug